---
- name: Test Ollama REST API
  hosts: all
  become: false
  vars:
    api_host: "http://localhost:8000"
    ollama_host: "http://localhost:11434"
  tasks:
    - name: Check if Ollama is running
      uri:
        url: "{{ ollama_host }}/api/health"
        method: GET
      register: health_check
      failed_when: health_check.status != 200
      ignore_errors: true

    - name: Print Ollama health check result
      debug:
        var: health_check

    - name: Wait for REST API to be available
      uri:
        url: "{{ api_host }}/health"
        method: GET
      register: api_health_check
      until: api_health_check.status == 200
      retries: 10
      delay: 2

    - name: Print API health check result
      debug:
        var: api_health_check

    - name: Test list models endpoint
      uri:
        url: "{{ api_host }}/models"
        method: GET
        return_content: yes
      register: models_response
      failed_when: models_response.status != 200 or 'models' not in models_response.json

    - name: Print models response
      debug:
        var: models_response.json

    - name: Test generate endpoint
      uri:
        url: "{{ api_host }}/generate"
        method: POST
        body_format: json
        body:
          prompt: "Hello, how are you?"
          model: "llama3"
          temperature: 0.7
          max_tokens: 100
        return_content: yes
      register: generate_response
      failed_when: generate_response.status != 200 or 'text' not in generate_response.json

    - name: Print generate response
      debug:
        var: generate_response.json

    - name: Test chat endpoint
      uri:
        url: "{{ api_host }}/chat"
        method: POST
        body_format: json
        body:
          messages:
            - role: "user"
              content: "Tell me a short joke"
          model: "llama3"
          temperature: 0.7
          max_tokens: 100
        return_content: yes
      register: chat_response
      failed_when: chat_response.status != 200 or 'message' not in chat_response.json

    - name: Print chat response
      debug:
        var: chat_response.json