---
- name: Test Ollama Shell Interface
  hosts: all
  become: false
  vars:
    ollama_host: "http://localhost:11434"
  tasks:
    - name: Check if Ollama is running
      uri:
        url: "{{ ollama_host }}/api/health"
        method: GET
      register: health_check
      failed_when: health_check.status != 200
      ignore_errors: true

    - name: Print health check result
      debug:
        var: health_check

    - name: Set up Python environment
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - pexpect

    - name: Test shell interface basic commands
      shell: |
        python -c '
import pexpect
import sys
import time

# Start shell interface
child = pexpect.spawn("python -m ollama_client.interfaces.shell.interactive --host {{ ollama_host }}")
child.expect("ollama>")

# Test models command
child.sendline("models")
index = child.expect(["Available Models", "Error"])
if index == 1:
    print("Error listing models")
    sys.exit(1)
child.expect("ollama>")

# Test info command
child.sendline("info")
child.expect("Ollama Session Info")
child.expect("ollama>")

# Test simple query
child.sendline("query Hello, how are you?")
index = child.expect(["Generating response", "Error"])
if index == 1:
    print("Error sending query")
    sys.exit(1)

# Wait for response to complete (may take time for LLM to respond)
time.sleep(5)
child.expect("ollama>", timeout=60)

# Test chat mode
child.sendline("chat Tell me a short joke")
index = child.expect(["Thinking", "Error"])
if index == 1:
    print("Error in chat mode")
    sys.exit(1)

# Wait for response to complete
time.sleep(5)
child.expect("ollama>", timeout=60)

# Test resetting chat
child.sendline("reset")
child.expect("Conversation history has been reset")
child.expect("ollama>")

# Exit shell
child.sendline("exit")
child.expect(pexpect.EOF)

print("Shell interface tests passed")
sys.exit(0)
        '
      register: shell_test
      failed_when: shell_test.rc != 0

    - name: Print shell test results
      debug:
        var: shell_test.stdout_lines