---
- name: Test Ollama REST API
  hosts: all
  become: false
  vars:
    api_host: "http://localhost:8000"
  tasks:
    - name: Wait for API to be available
      uri:
        url: "{{ api_host }}/health"
        method: GET
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 2

    - name: Test list models endpoint
      uri:
        url: "{{ api_host }}/models"
        method: GET
        return_content: yes
      register: models_response
      failed_when: models_response.status != 200 or 'models' not in models_response.json

    - name: Print models response
      debug:
        var: models_response.json

    - name: Test generate endpoint
      uri:
        url: "{{ api_host }}/generate"
        method: POST
        body_format: json
        body:
          prompt: "Hello, how are you?"
          model: "llama3"
          temperature: 0.7
          max_tokens: 100
        return_content: yes
      register: generate_response
      failed_when: generate_response.status != 200 or 'text' not in generate_response.json

    - name: Print generate response
      debug:
        var: generate_response.json